### ISSUE TITLE
Adding support for multiple levels of log

### ISSUE THREAD

**Issue by ClF3** [un-lock-able/cloudflare-ddns-rust#1]
### **Feature request**

Adding an option in the config file to allow users to customize the log level

### **Motivation**

By default the program only saves ERRORs (maybe also WARNINGs) into the log file. If I gave the "--config" parameter, then it would simply output everything both to the terminal and to the log file.
So maybe we can give users an option to customize the level of the log, such as "Debug", "Info", "Warning", "Error". So that they can keep only the logs they want

**Comment by un-lock-able** [comment]
The reason why I did not add the feature of changing verbosity in the config file is that in the case of missing or corrupted config file, the error log have to be outputed to somewhere. Because of this, setting up the logging functionality must be prior to reading any config file. I would consider to try to allow controlling verbosity using command line arguments.

**Comment by un-lock-able** [comment]
Fixed and merged to main. Will be available in the next release.
